#!/usr/bin/env sh
xset r rate 200 50 &
export XDG_SESSION_TYPE=x11
export XDG_CURRENT_DESKTOP=swm
export XDG_SESSION_DESKTOP=swm
export XMODIFIERS=@im=fcitx
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export SDL_IM_MODULE=fcitx
export GLFW_IM_MODULE=fcitx
# unset SSH_ASKPASS
# export __GLX_VENDOR_LIBRARY_NAME=nvidia
# export __NV_PRIME_RENDER_OFFLOAD=1 
feh --bg-scale ~/.config/wallpapers/wave.png &
fcitx5 &
swm_bar &
copyq &
# xrandr --output DP-2 --mode 1920x1080 --rate 144.00
while type swm >/dev/null; do swm && continue || break; done
exec swm
