srwm.spawn_once("xset r rate 150 50 &")
srwm.spawn_once("copyq &")
srwm.spawn_once("feh --bg-fill ~/.config/wallpapers/distort.jpg &")
srwm.spawn_once("flameshot &")
srwm.spawn_once("fcitx5 &")
-- srwm.spawn_once("pulseaudio --start &")
srwm.key.bind("Mod4", "space", function()
	srwm.spawn("rofi -show drun -theme $HOME/.config/rofi/launcher.rasi")
end)

srwm.key.bind("Mod4+Mod1", "s", function()
	srwm.spawn("flameshot full")
end)

srwm.key.bind("Mod4+Shift", "s", function()
	srwm.spawn("flameshot gui")
end)

srwm.key.bind("Mod4", "l", function()
	srwm.spawn("slock")
	srwm.spawn("systemctl suspend")
end)

srwm.key.bind("Mod4", "v", function()
	srwm.spawn("copyq menu")
end)
