#!/usr/bin/env bash

# Current Theme
dir="$HOME/.config/rofi/"
theme='powermenu'

# CMDs
uptime="`uptime -p | sed -e 's/up //g'`"
host=`hostnamectl hostname`

# Options
shutdown=' Shutdown'
reboot=' Reboot'
lock=' Lock'
logout='󰍃 Logout'
sleep=' Sleep'
# Rofi CMD
rofi_cmd() {
	rofi -dmenu \
		-p "$host" \
		-mesg "Uptime: $uptime" \
		-theme ${dir}/${theme}.rasi
}

# Pass variables to rofi dmenu
run_rofi() {
	echo -e "$lock\n$logout\n$sleep\n$reboot\n$shutdown" | rofi_cmd
}

# Actions
chosen="$(run_rofi)"
case ${chosen} in
    $shutdown)
		shutdown -P now
        ;;
    $reboot)
		reboot
        ;;
    $lock)
		swaylock -f
        ;;
    $logout)
		swaymsg exit
        ;;
    $sleep)
		swaylock -f && systemctl suspend
        ;;
esac
